tps-message: "<#656b96>TPS <gray>(1s - 1m - 5m)<#656b96>: <#949bd1><tps>"
ping-message: "<#656b96>Pong! <gray><player> ping<#656b96>: <#949bd1><ping>ms"
tps-kick:
  #what TPS players should all be kicked at
  tps: 8.0

  #server to transfer players to when TPS is too low
  transfer-host: "hold.feather64.net"
  transfer-port: 25564

  #TPS threshold for canceling a scheduled kick (if TPS recovers above this value)
  cancel-threshold: 16.0

  #kick warning message
  warn-message: "<#c0a1d1>Trash TPS detected - Everyone will be transferred to the Holding World"

  #transfer/kick message (shown if transfer fails and player is kicked instead)
  kick-message: "\n<white>• <#c0a1d1>Server TPS issues - Kicked"

  #kick cancel message
  cancel-message: "<white>• <#c0a1d1>Server TPS recovered - canceled transfer  :  ]"

portal-spawn-reduction:
  
  # TPS threshold below which to reduce portal spawns
  tps-threshold: 20.0
  
  # Percentage of normal spawn rate to allow (5 = 5% of normal spawns)
  spawn-rate: 5

kill-dense:
  # tps must be this value or below for kill-dense to run
  tps: 18.0

  # Spherical range (radius in blocks) for calculating nearby entities around an entity
  # This checks in all directions (X, Y, and Z) forming a sphere
  range: 2.5

  # Required entity count within range to be considered "dense"
  dense-count: 20

  #Chance as a % that a dense mob will be killed/removed
  chance: 25

  # Message sent to ops when tps is low
  message: "<DARK_GRAY> TPS: <roundedtps> | Dense Mobs Killed: <killedmobscount>/<densemobstotal>"


  # List of entity types that will be considered for removal
  killable-entities:
    - "COW"
    - "PIG"
    - "CHICKEN"
    - "RABBIT"
    - "SHEEP"
    - "SQUID"
    - "GLOW_SQUID"
    - "ENDERMAN"
    - "PIGLIN"
    - "CAVE_SPIDER"
    - "SPIDER"
    - "BLAZE"
    - "CREEPER"
    - "DROWNED"
    - "GHAST"
    - "GUARDIAN"
    - "PILLAGER"
    - "SKELETON"
    - "SLIME"
    - "MAGMA_CUBE"
    - "VINDICATOR"
    - "WITCH"
    - "WITHER_SKELETON"
    - "ZOMBIE"
    - "TURTLE"
    - "FROG"
    - "STRIDER"
    - "BEE"
    - "IRON_GOLEM"
    - "SHULKER"
    - "CREAKING"
